@extends('layouts.website.site')
@section('content')

    <br>
    <div class="row justify-content-md-center">
        <div class="card">
            <div class="card-body text-left">
                
<big>About TagiMagi.com - the all-purpose matching website.<br> A personal website by <a href=https://www.tagimagi.com/donate>Marcus Wilson</a></big>
<Br><Br>
    
<b>Beyond Privacy</b><Br><Br>

TagiMagi.com goes beyond privacy by  not requiring personal information, giving you the option to choose to put in (or not put in) whatever you wish: No email needed. No phone number needed. No registration required. Of course, we will incorporate means where you can register if you so wish. This will help aid in trust. However, trust and truth are different things, so trust alone is not our focus, but rather: truth. The only thing that may be required in the future is to ensure users know the IP location you are posting from matches the submitted profile. But as of now, there are no requirements.  We want to make it as least intrusive as possible.<Br><Br>
<b>Proactive Charity</b><Br><Br>  
The website proactively provides the help needed in which it will ensure everyone will have the means to make their right connections at no cost. At TagiMagi.com we believe right connection is not only a right but a requirement for the well-being of civilization and for individuals. By removing the resistance to right-connection (such as the need for advertising) we aid in helping people, which will normally cost lots of money and time. Most stories of abundance begins with the right connections.   <Br><Br>
<b>Balanced and Proportional Contribution and Distribution</b><Br><Br>
Unlike most popular websites, TagiMagi.com will incorporate balance distribution and contribution (and recognition). Most websites are all about becoming popular and showing the world specific internet numbers linked to specific things, which can easily be manipulated and which many people pay for.  With this also comes propaganda. However, TagiMagi.com is a propaganda-free website.  In addition to being propaganda free we are also hate speech free, as we are not a communicative platform but a matching platform. <Br><Br>
<b>Automatching</b><Br><Br>
Gone will be the days of only searching and advertising; gone will be the days of only chasing and attracting.  TagiMagi.com will not be primarily a masculine/feminine driven system but a balanced system that will incorporate automatching. This means, selecting for mates, for example, will also be done by the system.  Many people get married and get divorced; many people do not make their ideal best connections.  This is because of the lack of precision matching and the resistance society puts on finding the right connections. As we mentioned, we are removing the resistance to ensure all are matched with the best of all possibilities. This begins with trusting the truth of our system, and you will love our matches, but we also understand many are conditioned to follow not what they want, but what others or their society has been conditioned to want, or even to fear what they actually can trust, and many other things. This needs to be addressed outside of TagiMagi.com.<Br><Br>

<b>GateKeeper-Free</b><Br><Br>
TagiMagi.com is a GateKeeper-Free website.  Unlike with most websites, humans are serving as gatekeepers. Gatekeeperism goes against our requirement for right-connection.  Additionally, humans are flawed in a sense that many are only gatekeeping to keep themselves, people like themselves, or their friends in positions of power, or doing it only so much so they have or maintain an upper hand.  We believe there are matches for all sorts of people, and by having a GateKeeper Free website, it means there are no biased, prejudiced humans behind our selection process. In fact, our only selection is balanced and proportional distribution and contribution so that you can have the most amount of right connections in the shortest possible time that you need.<Br><Br>
<b>We don't Sacrifice the Good because of the Bad</b><Br><Br>
Most organizations sacrifice good people because of the few deeds of the bad.  We believe in precise problem solving, not sloppy problem solving attacking entire groups of people because of a few bad apples. Additionaly, our focus is not only on solutionism, as there is not always proof that the "bad" have really come from where it is claimed; "the bad" could have come from the one trying to offer the solution for more money, power, and control.  Regardless of the truth about it, at TagiMagi.com we will use the minimum amount of "sacrificing the group because of the few" as possible.<Br><Br>
<b>It's Safe because it's Open</b><Br><Br>
It is safe because there is no secret. TagiMagi.com is like being out in the real world, where anyone can hold up a sign. Anyone can make a tag post about anything.  Therefore, they don't know if they are communicating with a police officer or the actual person.  There can be lots of undercover security officers (or even regular people) in which TagiMagi.com can be used to catch all who would not be caught as easily if they were doing it on some secret, dark web website. However, TagiMagi.com is not against privacy, this is why we have the option to choose what you reveal.  And because we are for privacy, as long as some people have more privacy than others, then it is only right that everyone has it; therefore, we will do what we can to incorporate more means to increase your privacy as well as safety.<Br><Br>
<b>It's Regulated Because all Unregistered posts are Automatically Deleted After Two Weeks</b><Br><Br>
Many sites have hate speech and news propanganda contaminating their site. While the big sites currently allow hate/inequality propaganda through news stories and sponsoring, but when it comes to hate speech, they end up removing or deleting individual posts, sometimes even removing and deleting entire profiles.  TagiMagi.com is self-regulated where it automatically replenishes itself regularly. There are no organizations paying for a news headline to get you and everyone to think or act in a certain way and there are no individuals trying to force their beliefs to get you to believe or act in a certain way.  TagiMagi.com is a equal exposure field for all whether or not one is popular or has lots of money. <Br><Br>

<b>Not Digital-Only or Social-Only Centric</b><br><br>
Tagimagi.com is not soley focused on digital or socialization. It includes both those things but TagiMagi.com is not a social network nor is it geared towards keeping humans only digitally focused. While we encourage people to use our site to find and communicate with people digitally and online, our site also has the option for communication and meeting people offline, and not only for collective socialization but also for collective action if that is what the individuals are looking for. Life is not only about talking together online but also acting together offline, and thus TagiMagi.com includes it.<br><br>


<b>Not Money-Only Centric</b><br><br>
For many sites, it is also only about exchanging certain types of money or cryptocurrency. Not everyone has or wants to use specific types of money or cryptocurrency or even money in general. But at TagiMagi.com individuals have the option to choose what type of currency they want to exchange with by simply putting the name of it as a tag in their profile.  And better yet, they have the option to not even use money or currency at all, maybe they're just looking to barter or work together and collectively share things.  At TagiMagi.com it is not centered around that you have to use money, crypocurrency, or exchange; you can if you want, but at TagiMagi.com you don't have to or don't even need to.<Br><Br>
<b>No Secret Spying</b><Br><Br>
For some reason, most of the big popular sites like to keep your stuff stored and have access to them so they can spy on you.  Why they want to spy on you, I have no idea.  The co-creator of TagiMagi.com (created along with everyone in the world because everything is connected) has no interest in spying and watching you. When someone wants to spy on you without you having the ability to also spy and watch them, that shows an imbalance. Although tag profiles are currently kept in a database before they are automatically and permanently deleted, they are searchable by all and there is no agenda to watch and spy on the world. And with everyone already openly posting on social networks, just about everything can be easily inferred about them through their long list of posts, pictures, likes, opinions, and connections.<Br><Br>
<b>TagiMagi can be used as an alternative or aid to many of the world's largest websites:</b><Br><Br>
All of the websites mentioned below are still useful and serve their purpose.  While TagiMagi.com can be used as an alternative to mostly all of them, it can also be used as an aid to them by helping you to get exposure to your posts on them. So, TagiMagi.com can also help promote the sites listed below and your posts on them in addition to being an alternative to them, but if you are specifically looking for alternatives TagiMagi can be to, here are some of them:<Br><Br>
<b>Craigslist Alternative</b><Br><Br> 
TagiMagi.com can be use as an alternative to craigslist. If CL staff constantly deletes your posts without explaination and for strange reasons, regardless of what email or phone number you use, and even when they abide by all the guidelines and are no different than all other posts on the site, then TagiMagi.com can be used as an alternative.  Some sites like to blame things on "an algorthim", which they would easily tweak if the algorthim didn't work for them personally. As mentioned, right connection is a necessary for every living thing.  Whether it be right food, right people, right locations, etc. TagiMagi.com does not interfer with that process.  Also, there is no registration required at TagiMagi.com, this means we do not keep your personal information or email, nor do we secretly cross-reference with other big sites. However, as mentioned, TagiMagi.com can not only be used as an alternative, it can also be used as an aid for craigslist.  For example, you can still use craigslist (considering it is useful for you) and use TagiMagi.com to promote your craigslist post or ad.<Br><Br>
<b>Google Ads Alternative</b><Br><Br>
The website can be used as a Google Ads alternative. Why spends hundreds or thousands of dollars to promote your stuff when you can easily, quickly, and for free post a tag profile at TagiMagi.com?  The benefits of TagiMagi.com is that not everyone has money to advertise, or maybe they don't even have a phone or email which google, as well as all the other big sites, require.<Br><Br>
<b>Google Alternative DuckduckGo Alternative Search Engine Alternative</b><Br><Br>
TagiMagi.com can be used as a search  engine alternative.  Why search the web for billions of websites when you can search TagiMagi.com which includes websites and much more (apps, physical locations, etc.), including those who do not have or want websites? It also (currently) includes posts you know are very recent (currently within 2 weeks). When you search websites on search engines, you could be getting things that are outdated or no longer as relevant.<Br><Br>
<b>Facebook Marketplace Alternative</b><Br><Br>
The website can be used as an alternative to facebook marketplace. However, instead of having to login and advertise, you can simply go to the website and post what you're looking to exchange.<Br><Br>
<b>Amazon.com Alternative</b><Br><Br>
TagiMagi.com can serve as an alternative to amazon.com, the worlds largest and most advanced marketplace.  If you are looking to buy or sell anything, you can easily create tag profiles for it.  But in addition to offering things, you can also request things: tangible or non tangible. Although amazon does have more services than just buying and selling, for that particular part of it, TagiMagi.com can be used as well.  Or, as mentioned, you can use TagiMagi.com to get free promotion on your amazon products.<Br><Br>  
<b>Instacart Alternative Uber Eats Alternative Grubhub Alternative</b><Br><Br>
The website can serve as an alternative to instacart.  While instacart is a great service connecting all the stores, it ignores individuals and smaller businesses.  With TagiMagi.com you can sell things from the comfort of your home and have someone deliver it to anyone (or vice versa).  Instacart only (currently) deals with big name brand stores.<Br><Br>
<b>Meetup Alternative</b><Br><Br>
TagiMagi.com can serve as an alternative to Meetup.com.  All one has to do is to put in a specfic location (anywhere in the world) and you can meet people at any time with specific interests.  On top of that, it is free, unlike with all the sites listed here. We believe right connection is a right and requirement for health and well being, this is why it is free.  <Br><Br>
<b>Match.com Alternative Tinder Alternative Dating Site Alternative</b><Br><Br>
TagiMagi.com can be used as an alternative to any dating site you can think of.  All one has to do is put the word/tag "dating" in the "interested in" section and people will be able to find all those interested in dating with the specific characteristics you choose. Also, many dating sites deal with only visual elements and are limited in the matching dimensions, but with TagiMagi.com, it is so clear, you can find someone with freckles and that loves to eat doritos, in addition to all the other matching dimensions all other sites provide.  Additionally, there is no cost and it is quick and efficient. All one has to do is post to the site their characteristics and/or the characteristics they are looking for. <Br><Br>
<b>Web Hosting Alternative Wix Alternative Bluehost Alternative Host Gator Alternative Go Daddy Alternative</b><Br><Br>
Most people create websites so they can have a place on web so that people can find them.  To get a website, it requires paying for a domain name, hosting, registration, and so much more.  The internet and domain system, along with its hosting, is a large money making system.  However, a lot of that money, when people buy websites and hosting, they rarely even get visits to their website or worse yet make the income to have the website pay for itself. So in essence, many people are getting websites and paying for hosting, domain names, security (which should already be included) - for decoration. Not all, there are alot, where paying for their own website turns a good investment, but there are no stats on this.  Just ask yourself, how much money did you put forth on getting a website, and how much money did it make you in return?  The money went in and not out.  Therefore, if you are looking to have people find you, just create a tag profile at TagiMagi.com for free, OR if you have or want a website and you want traffic, you can easily promote your website by including your website in your tag profile.<Br><Br>
<b>Alternative to Tiktok Alternative to Youtube Alternative to Vimeo Alternative Instagram Alternative</b><Br><Br>
TagiMagi can be used as an alternative to any video sharing site, except TagiMagi.com does not host videos, pictures or anything.  Instead, you can post your video or picture on your own personal website, and to have others find your video or picture, you can simply tag your tag profile as being a picture or video.  On sites like youtube,  only youtube videos are shown when you search; on sites like instagram, only instagram pictures and videos are shown, but TagiMagi.com can show links to videos uploaded to anywhere, including your own website or some other video hosting website. Therefore, to get exposure to your video, you don't have to upload to any of those websites, you can upload to your own website.  Also, those websites do nothing to balance distribution and contribution. They are more concerned with internet numbers and believe in only focusing quality and opportunity rather than also expanding quality and opportunity.  However, TagiMagi.com ensures you get real views, not fake views with fake numbers for your videos or pictures, regardless of where you post it, as long as you make the appropriate tags for others to find it. But as mentioned previously, TagiMagi.com is not a replacement for any website, it can be used as an aid to your youtube, tiktok, instagram, etc. to ensure you get the exposure you need.<Br><Br> 
<b>Web3 Alternative</b><Br><Br>
TagiMagi.com's mobile profiles, including word and sequences, will condense and decentralize information not only on the computer, but off the computer.  Decentralized software is useless without also having decentralized hardware and computers.  TagiMagi.com will work to ensure your hardware is also decentralized, but since it is currently only a website, its mobile profiles and condensed information sequences will allow you to have a portable profile on and off the internet. Our unique knowledge sequences will allow you to condense much more information than traditional website and profiles, as well as perform mathematical and more precision functions in comparing them. Additionally, we don't want or claim to own your profile or information.  Web3 is, in one sense, all about individual ownership, but this is because for some reason "Web2" sites wanted others to believe they "own" your information, and therefore made it as a "policy" in Web2's internet society.  Well, we don't own your info nor do we want it, even if we said we did "own it", it's still yours. Also, since it is open, everyone has access to it, so there is nothing to pay for.<Br><Br>
<b>Offerup Alternative Classified Ads Alternative</b><Br><Br>
Just like with Craigslist, TagiMagi.com can be used as an alternative to offerup.com. Just post the tag profile of what you're offering (or requesting) and you're good to go.<Br><Br>
<b>Uber Alternative Lyft Alternative</b><Br><Br>
TagiMagi.com can be used as an alternative to Uber or Lyft.  All one needs to do is add an offer or request for a ride to anywhere in one's profile and the results will immediately come up.<Br><Br>
<b>Etsy Alternative</b><Br><Br>
If you're looking to sell artwork, or anything specfic related to arts and crafts, simply tag your profile with artwork and crafts, and your profile will appear on <b>TagMagi.com<Br><Br>



            </div>
        </div>
    </div>


@endsection